# fly.toml app configuration file for Discord bot
app = "dictionary-bot"
primary_region = "ord"  # Chicago region (close to NIU)

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  # Environment variables (non-secret ones only)
  # Add any non-sensitive config here if needed

[processes]
  worker = "python main.py"

[deploy]
  strategy = "immediate"

# No [[services]] section needed since Discord bots don't serve HTTP traffic
# No PORT needed since we're not running a web server
