# fly.toml app configuration file for Discord bot
app = "dictionary-bot"
primary_region = "ord"  # Chicago region (close to NIU)

[build]
  # Remove the 'builder' line to let Fly.io use your Dockerfile.
  # The presence of a Dockerfile in the root of your repo is enough.

[env]
  # Environment variables (non-secret ones only)
  # Add any non-sensitive config here if needed

[processes]
  # Update the worker process to match the Dockerfile CMD
  worker = "python -m src.main"

[deploy]
  strategy = "immediate"

# No [[services]] section needed since Discord bots don't serve HTTP traffic
# No PORT needed since we're not running a web server